#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Android.Resource", IsApplication=true)]

namespace App.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int blue = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int green = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int left_arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int right_arrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001f
			public const int Licensure = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int List = 2131165213;
			
			// aapt resource value: 0x7f07001b
			public const int Name = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int Price = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int Search_button = 2131165209;
			
			// aapt resource value: 0x7f070020
			public const int back_button = 2131165216;
			
			// aapt resource value: 0x7f070012
			public const int bottom_space = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int dialog_contact = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int dialog_purchase = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int imageView1 = 2131165196;
			
			// aapt resource value: 0x7f070014
			public const int licensure_button = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout1 = 2131165192;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout2 = 2131165207;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout3 = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int makeHeader = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int makeSpinner = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int make_spinner = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int partHeader = 2131165205;
			
			// aapt resource value: 0x7f070006
			public const int partNameSpinner = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int partText = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int part_spinner = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int searchButton = 2131165191;
			
			// aapt resource value: 0x7f070018
			public const int space1 = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int space2 = 2131165210;
			
			// aapt resource value: 0x7f07000b
			public const int space3 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int space4 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int space5 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int space6 = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int top_space = 2131165193;
			
			// aapt resource value: 0x7f070021
			public const int tos = 2131165217;
			
			// aapt resource value: 0x7f070013
			public const int tos_button = 2131165203;
			
			// aapt resource value: 0x7f07001e
			public const int viewpager = 2131165214;
			
			// aapt resource value: 0x7f070023
			public const int yearHeader = 2131165219;
			
			// aapt resource value: 0x7f070004
			public const int yearSpinner = 2131165188;
			
			// aapt resource value: 0x7f070022
			public const int year_fragment = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int year_spinner = 2131165220;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MakeFragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PartFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PartListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PartsListLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ViewPagerActivity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int webview_Licensure = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int webview_ToS = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int YearFragment = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
